name: CI
on:
  pull_request:
    branches-ignore:
      - master

jobs:
  continous-integration:
    name: CI
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - run: yarn install --prod
      - name: lint
        run: yarn lint
      - name: tests
        run: yarn test
