name: develop CI/CD
on:
  pull_request:
    branches: [develop]

jobs:
  continous-integration:
    name: CI
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: lint
        run: yarn lint
      - name: tests
        run: yarn test

  release-commit:
    name: Relase commit
    runs-on: [ubuntu-latest]
    needs: [continous-integration]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - uses: prxg22/version-bump-action@v1.0.1
        with:
          head-branch: develop
          base-branch: master
          github-token: ${{secrets.GITHUB_TOKEN}}

  # deploy-beta:
  #   name: Deploy beta
  #   runs-on: [ubuntu-latest]
  #   needs: [continous-integration, release-commit]
  #
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1.1.0
  #       with:
  #         version: 12.x
  #     - name: install dependencies
  #       run: yarn install --prod
  #     - name: build
  #       run: yarn build
  #     - name: deploy
  #       run: yarn deploy
