name: develop CI/CD
on:
  pull_request:
    branches:
      - master

jobs:
  continous-integration:
    name: CI
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - run: yarn install --prod
      - name: lint
        run: yarn lint
      - name: tests
        run: yarn test

  release-commit:
    name: Relase commit
    runs-on: [ubuntu-latest]
    needs: [continous-integration]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - uses: prxg22/version-bump-action@v1.0.1
        with:
          head-branch: develop
          base-branch: master
          github-token: ${{secrets.GITHUB_TOKEN}}
