name: master CI/CD
on:
  push:
    branches: [master]

jobs:
  continous-integration:
    name: CI
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: lint
        run: yarn lint
      - name: tests
        run: yarn test

  push-tag:
    name: Push new version's tag
    runs-on: [ubuntu-latest]
    needs: [continous-integration]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - uses: prxg22/push-package-version-tag-action@1.0.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          tag-prefix: v

  # deploy-beta:
  #   name: Deploy beta
  #   runs-on: [ubuntu-latest]
  #   needs: [continous-integration, release-commit]
  #
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1.1.0
  #       with:
  #         version: 12.x
  #     - name: install dependencies
  #       run: yarn install --prod
  #     - name: build
  #       run: yarn build
  #     - name: deploy
  #       run: yarn deploy
