name: master CI/CD
on:
  push:
    branches:
      - master

jobs:
  continous-integration:
    name: CI
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: lint
        run: yarn lint
      - name: tests
        run: yarn test

  release:
    name: Push new version's tag and release it
    runs-on: [ubuntu-latest]
    needs: [continous-integration]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - run: yarn install --prod
      - name: build
        run: yarn build
      - uses: prxg22/push-package-version-tag-action@master
        id: push
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          tag-prefix: v
      - run: echo ${{steps.push.outputs.created-tag}}
      - name: publish
        if: steps.push.outpts.created-tag
        run: |
          echo //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}} >> .npmrc
          yarn publish --non-interactive
