name: master CI/CD
on:
  push:
    branches:
      - master

jobs:
  continous-integration:
    name: CI
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: lint
        run: yarn lint
      - name: tests
        run: yarn test

  push-tag:
    name: Push new version's tag
    runs-on: [ubuntu-latest]
    needs: [continous-integration]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - run: yarn install --prod
      - uses: prxg22/push-package-version-tag-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          tag-prefix: v


  release:
    name: Release tag
    runs-on: [ubuntu-latest]
    needs: [continous-integration, push-tag]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - run: echo //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}} >> .npmrc
      - run: yarn publish --non-interactive
